### ISSUE TITLE
Need a new package name

### ISSUE THREAD

**Issue by jakevdp** [PrincetonUniversity/FastTemplatePeriodogram#18]
[pyftp](https://pypi.python.org/pypi/pyftp) is already taken.

**Comment by johnh2o2** [comment]
Changed this to `tempfit`, which I couldn't find on PyPi, so hopefully this resolves that issue? If you're alright with `tempfit`, go ahead and close this.

**Comment by jakevdp** [comment]
I'm worried ``tempfit`` is a bit generic, and "temp" in this context makes me think "temporary". How would you feel about ``ftperiodogram``?

**Comment by johnh2o2** [comment]
Changed to `ftperiodogram` -- still a bit awkward to me, but I think it's the best either of us have come up with at this point... if you're happy with `ftperiodogram` feel free to close.

**Comment by jakevdp** [comment]
Sounds good. I don't love it, but I don't have better ideas at the moment :smile:
