### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by jakevdp** [PrincetonUniversity/FastTemplatePeriodogram#22]
Recent commits make tests pretty slow (1.5 minutes on my computer): most of this time is spent in ``test_modeler.py``. If there are ways to speed this up (e.g. by not computing such large grids) it would facilitate further development.

**Comment by johnh2o2** [comment]
I've noticed this too -- I simplified the `test_modeler` script a bit, which brings the speed from 86s -> 36s on my laptop, but things are still on the slow side. I'll have to look into how some of the API changes have affected speed. It might make sense to make things a bit less robust on the root finding if it means a significant speed improvement.

**Comment by johnh2o2** [comment]
The entire test suite now takes 26.13s on my laptop -- do you think this is fast enough? What would you say is a reasonable upper bound for how much time it takes to run `make test`?

**Comment by jakevdp** [comment]
sounds good!
