### ISSUE TITLE
Use Polynomial API in PseudoPolynomial?

### ISSUE THREAD

**Issue by jakevdp** [PrincetonUniversity/FastTemplatePeriodogram#27]
Is there a good reason to avoid the Polynomial API rather than the low-level routines in ``pseudo_poly.py``? It may be a bit slower, but I doubt the difference would be significant overall.

Using that API would make the code much easier to understand and maintain in the long-run. Perhaps once we have some comprehensive benchmarks, we could think about translating parts of this.

**Comment by johnh2o2** [comment]
Agreed! I've incorporated `Polynomial` instances throughout.
