### ISSUE TITLE
Concern: ``remove_zeros`` in ``pseudo_poly``

### ISSUE THREAD

**Issue by jakevdp** [PrincetonUniversity/FastTemplatePeriodogram#28]
This seems like a bit of a hack to me, and I'm worried about its implications. It would be useful to have this tunable at the highest level, so we can make sure it's not impacting results negatively.

**Comment by johnh2o2** [comment]
Hi Jake,

I agree with you here -- it's leftover from when I was trying to figure out the source of failures when recovering closely-spaced roots in the pseudo polynomial module. That's all been fixed now, and I've replaced the arrays of coefficients `Polynomial` instances to make things easier.
