### ISSUE TITLE
Rename FastTemplateModeler

### ISSUE THREAD

**Issue by jakevdp** [PrincetonUniversity/FastTemplatePeriodogram#29]
I think it would make sense to rename the top-level method to ``FastTemplatePeriodogram``, to match the name of the package. Additionally, reading through the code I was initially confused by the names ``TemplateModel`` and ``FastTemplateModeler``, because at first glance it sounds like the two classes should do the same thing, just at different speeds. A name change would prevent that confusion as well.

Thoughts?

**Comment by johnh2o2** [comment]
I've changed all `Modeler` instances to `Periodogram` instances.

**Comment by jakevdp** [comment]
👍
