### ISSUE TITLE
Multiplication of `PseudoPolynomial` with `Polynomial` is not commutative

### ISSUE THREAD

**Issue by johnh2o2** [PrincetonUniversity/FastTemplatePeriodogram#30]
```python

a = PseudoPolynomial(p=[ 0, 1, 4 ], q=[2, 3, 0], r=0)
b = Polynomial([ 1, 4, 6 ])

prod_ab = a * b
prod_ba = b * a
```

The `a*b` product is a `PseudoPolynomial`, however the `b*a` product is a `Polynomial`; I'm pretty sure this is because Python will attempt to evaluate `b.__mul__(a)` before `a.__rmul__(b)`, and I don't see any way to work around that...

Any suggestions or is this a necessary evil? It doesn't affect the rest of the code in any way, and the "rest of the code" is the entire reason the `PseudoPolynomial` class exists in the first place, so this is an extremely minor problem.

**Comment by jakevdp** [comment]
Hmm... I tried it out (Python 3.6, Numpy 1.12) and I get the same result either way. What package versions do you see this on?

**Comment by johnh2o2** [comment]
Now irrelevant (no pseudopolynomial stuff!)
