### ISSUE TITLE
Use ``nfft`` rather than ``pynfft``?

### ISSUE THREAD

**Issue by jakevdp** [PrincetonUniversity/FastTemplatePeriodogram#31]
I just released a lightweight package that computes fast NFFTs, using only ``numpy`` and ``scipy`` rather than a custom compiled package. It's a much lighter dependency (pure Python, pip installable), and the speed is comparable to ``pynfft`` (faster in many cases).

Take a look, and let me know what you think. It might be worth changing to depend on that just for the sake of simplifying our installation requirements here.

**Comment by jakevdp** [comment]
Oh, here's the link: http://github.com/jakevdp/nfft/

**Comment by johnh2o2** [comment]
Hey Jake -- replaced pynfft with nfft. Thanks for a great NFFT implementation!

**Comment by jakevdp** [comment]
Great!
