### ISSUE TITLE
Cannot Instantiate RRLyrae Modeler

### ISSUE THREAD

**Issue by jakevdp** [PrincetonUniversity/FastTemplatePeriodogram#6]
I'm trying to do some basic imports to start to understand how the code works, and I'm running into errors immediately. This error comes up on both Python 2.7 and Python 3.6. Any ideas what might be happening here?

```python
In [1]: from pyftp.rrlyrae import FastRRLyraeTemplateModeler

In [2]: modeler = FastRRLyraeTemplateModeler()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-06871de6eacb> in <module>()
----> 1 modeler = FastRRLyraeTemplateModeler()

/Users/jakevdp/github/PrincetonUniversity/FastTemplatePeriodogram/pyftp/rrlyrae.pyc in __init__(self, filts, redo, **kwargs)
     92         self.params['redo'] = redo
     93         self.params['filts'] = self.filts
---> 94         self._load_templates()
     95 
     96     def _load_templates(self):

/Users/jakevdp/github/PrincetonUniversity/FastTemplatePeriodogram/pyftp/rrlyrae.pyc in _load_templates(self)
     97         pars = [ 'filts', 'template_fname', 'errfunc', 'stop', 'nharmonics', 'redo' ]
     98         kwargs = { par : self.params[par] for par in pars if par in self.params }
---> 99         self.templates = get_rrlyr_templates(**kwargs)

/Users/jakevdp/github/PrincetonUniversity/FastTemplatePeriodogram/pyftp/rrlyrae.pyc in get_rrlyr_templates(template_fname, errfunc, stop, filts, nharmonics, redo)
     41         ftp_templates = { ID : Template(phase=T, y=Y, errfunc=errfunc,
     42                                         nharmonics=nharmonics, stop=stop).precompute() \
---> 43                                     for ID, T, Y in zip(IDs, Ts, Ys) }
     44         #print "done"
     45         if not template_fname is None:

/Users/jakevdp/github/PrincetonUniversity/FastTemplatePeriodogram/pyftp/rrlyrae.pyc in <dictcomp>((ID, T, Y))
     41         ftp_templates = { ID : Template(phase=T, y=Y, errfunc=errfunc,
     42                                         nharmonics=nharmonics, stop=stop).precompute() \
---> 43                                     for ID, T, Y in zip(IDs, Ts, Ys) }
     44         #print "done"
     45         if not template_fname is None:

/Users/jakevdp/github/PrincetonUniversity/FastTemplatePeriodogram/pyftp/modeler.pyc in precompute(self)
    213         #print self.cn
    214         #print self.sn
--> 215         self.pvectors = ftp.get_polynomial_vectors(self.cn, self.sn, sgn=1)
    216 
    217         #print "computing ptensors"

/Users/jakevdp/github/PrincetonUniversity/FastTemplatePeriodogram/pyftp/pseudo_poly.pyc in get_polynomial_vectors(cn, sn, sgn)
    346     A_n, B_n, and their derivatives
    347     """
--> 348     A = ABpoly(cn, sn, sgn, 0)
    349     B = ABpoly(cn, sn, sgn, 1)
    350 

/Users/jakevdp/github/PrincetonUniversity/FastTemplatePeriodogram/pyftp/pseudo_poly.pyc in <lambda>(c, s, sgn, alpha)
    278 ABpoly = lambda c, s, sgn, alpha : [ Afunc_pp(n+1, C if alpha == 0 else  S,
    279                                                  S if alpha == 0 else -C, sgn) \
--> 280                                        for n, (C, S) in enumerate(zip(c, s)) ]
    281 
    282 # Hardcoded, should probably be double checked but this

/Users/jakevdp/github/PrincetonUniversity/FastTemplatePeriodogram/pyftp/pseudo_poly.pyc in <lambda>(n, p, q, sgn)
    270 # An (or Bn) as a PseudoPolynomial
    271 Afunc_pp = lambda n, p, q, sgn : PseudoPolynomial(   \
--> 272                                         p=         p * np.array(chebyt(n).coef)[::-1],
    273                                         q= - sgn * q * np.array(chebyu(n-1).coef)[::-1] \
    274                                                if n > 0 else np.array([0]),

/Users/jakevdp/anaconda/envs/ftp27/lib/python2.7/site-packages/scipy/special/orthogonal.pyc in chebyt(n, monic)
   1201     kn = 2**(n - 1)
   1202     p = orthopoly1d(x, w, hn, kn, wfunc, (-1, 1), monic,
-> 1203                     lambda x: eval_chebyt(n, x))
   1204     return p
   1205 

/Users/jakevdp/anaconda/envs/ftp27/lib/python2.7/site-packages/scipy/special/orthogonal.pyc in __init__(self, roots, weights, hn, kn, wfunc, limits, monic, eval_func)
    143             kn = 1.0
    144         self.__dict__['normcoef'] = mu
--> 145         self.__dict__['coeffs'] *= kn
    146 
    147         # Note: eval_func will be discarded on arithmetic

TypeError: ufunc 'multiply' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''
```

**Comment by johnh2o2** [comment]
I can replicate this on my end as well -- here's whats happening:

* Currently, there is a `stop` parameter and a `nharmonics` parameter. If `stop` is specified, it picks the number of harmonics such that the `RMS(template - template(nharmonics=H)) / RMS(template) < stop`. 
* By default, `stop` is specified (using `stop=1E-2`). I was trying to find a way to automatically pick a reasonable value of H for a given template, but this can cause H to be large if (1) the template is not well approximated by a small number of harmonics, (2) the function that generates the `phase` and `y` values from the Fourier coefficients is reversing the template (I'll check this). 
* When `scipy.special.chebyt(n)` is called with a large enough `n` (this happens to be 65), something breaks.

For now, I just changed the defaults to `stop=None, nharmonics=6`, but that's not a real fix. 

This illustrates the desperate need for some sort of unit testing, which I have never actually implemented before. I would be grateful if you could give some advice about this. 

Additionally, this `stop` parameter seems awkward and I think maybe we should just get rid of it altogether and let the user compute the number of harmonics they want to use.

Any thoughts?

**Comment by jakevdp** [comment]
I'd be happy to put some effort into unit testing... I was running this to try to get started on that :smile: I think it's best to start from the ground-up, testing the individual utility functions behind the code itself.

To that end: do you have any test cases you were using along the way when developing the guts of the code (i.e. making sure the NFFT version of something matches the slow-but-direct version?) If so, it would probably be easiest to adapt some of those into unit tests.

**Comment by jakevdp** [comment]
Another option would be to start with some integration tests – i.e. high-level tests of input and output from, e.g. the rrlyrae modeler class.

Reading through the code, I think there are some places where numpy vectorization could be used to make things much faster, but I hesitate to change anything until we have such tests in place.

**Comment by johnh2o2** [comment]
>do you have any test cases you were using along the way when developing the guts of the code (i.e. making sure the NFFT version of something matches the slow-but-direct version?)

That is exactly what I was doing originally, but have since gotten rid of all of the code that computed direct summations to compare with the NFFT....it's probably still in an earlier commit. I'll try to dig that out and see what was there and if we can adapt that or if it's easier to just start from scratch with the current implementation in mind.

> Another option would be to start with some integration tests – i.e. high-level tests of input and output from, e.g. the rrlyrae modeler class.

That I think would be important too, in addition to some lower-level tests.

> Reading through the code, I think there are some places where numpy vectorization could be used to make things much faster, but I hesitate to change anything until we have such tests in place.

Awesome!

**Comment by jakevdp** [comment]
Hey @johnh2o2 – I'm really struggling coming up with any sort of unit tests here, because the functionality is so poorly documented and there are no examples of intended use.

For example, I thought I'd tackle unit tests of the ``Template`` class, but came away very confused about what the intended inputs are, and what the intended outputs are.  There seem to be two "modes" of creating a template, but it's not clear what's required for each (short of reading the code, which is just a long string of assignments and function calls without any real high-level reference to what's going on)

As for the output, it seems like the class stores some values that are relevant (maybe the phase, y, and best_fit_y?) but it's not clear to me what values are meant for internal use, and what values are meant to be "outputs" of the class.

All of that makes it very difficult for me to write any sort of meaningful test: a test involves specifying some inputs and checking that the outputs are as expected, and I'm uncertain of what either the inputs or outputs should be!

I'm happy to work on the unit testing framework, but I'll need your help in understanding the code. Could you give me a series of short, self-contained snippets that demonstrate how ``Template`` is meant to be used, along with the expected output? Given that, I could start on the test framework so you can get an idea of what it would look like.

**Comment by johnh2o2** [comment]
@jakevdp -- that's helpful input! I would like the code to be as intuitive, portable, simple, and Pythonic as it can be. I'll try to give you an idea of what the `Template` class attributes are and how I intended them to be used. Any suggestions about coding practices or a simpler/more logical implementation that would make things easier on you (and therefore everyone else), would be great!

Here's where things currently stand. But I've been meaning to revisit this class and clean it up, and running this works but the `rms_resid_over_rms` doesn't seem to be right. I'm running off to lunch now but I figured I'd send you this for now.

## `Template` class

```python
# Should we use a `template.py` module instead?
from pyftp.modeler import Template, FastTemplateModeler
import numpy as np

# BASICS
# ======

# You can define a template in two ways
# (1) By (phase, y) -- e.g. the Sesar et al. 2010 templates
phase = np.linspace(0, 1, 100)
y     = np.cos(2 * np.pi * phase) + 0.5 * np.sin(4 * np.pi * phase)

template_phase = Template(phase=phase, y=y)

# (2) By fourier amplitudes (cn, sn)
cn = [ 1., 0.  ]
sn = [ 0., 0.5 ]

template_fourier = Template(cn=cn, sn=sn)

# In order to speed up the fast template periodogram,
# I optionally precompute certain values that depend only
# on the template and not on the data, i.e.
#   pvectors, ptensors
#
# The precompute() function also computes 
#   best_fit_y, rms_resid_over_rms
template_phase.precompute()

# ATTRIBUTES
# ==========

# template_fourier.cn_full, template_fourier.sn_full
#
#   If the template is defined by Fourier amplitudes
#   the template stores the full template so that the
#   user can optionally use a smaller number of harmonics
#   if desired by calling, e.g.
template_fourier.set_nharmonics(1)

# Now, 
print("cn, sn = ", template_fourier.cn, template_fourier.sn)

# but the template still keeps the other harmonics
print("cn_full, sn_full = ", template_fourier.cn_full, template_fourier.sn_full)

# so that I can go back to the full template
template_fourier.set_nharmonics(2)

# Now, 
print("cn, sn = ", template_fourier.cn, template_fourier.sn)

# template_*.best_fit_y
#   best_fit_y is the truncated template aligned with 
#   the full template, so
template_fourier.set_nharmonics(1)
residual = template_fourier.best_fit_y - template_fourier.y 
print("Template(H=1) - Template(H=2) = ", residual)

# errfunc
#    errfunc is a function that takes (cn, sn, phase, y) as arguments 
#    and returns some measure of similarity
#
#    this is relevant only when you've specified the `stop` parameter
#    and have defined the template by (phase, y). In this case, when 
#    precompute() is called, the number of harmonics are determined
#    automatically.
#         1. first, the FFT of the (phase, y) data is computed: cn, sn = FFT(y)
#         2. starting with H=1, 
#         3. set err = errfunc(cn[:H], sn[:H], phase, y)
#         4. if err < stop, then nharmonics = H, else H+=1 and repeat 3.
# 		  

# I.e., this process:
stop = 1E-2
for H in range(10):
	template_phase.set_nharmonics(H)
	template_phase.precompute()
	print("H=", H, "rms(T(H=H) - T(full)) / rms(T(full)) = ", template_phase.rms_resid_over_rms)
	if template_phase.rms_resid_over_rms < stop:
		break

# can be done automatically by setting
template_phase.stop = 1E-2
template_phase.precompute()
```

**Comment by jakevdp** [comment]
Awesome, thanks! I'm just about to finish a PR with a couple unit tests of the things I could decipher :smile:

**Comment by johnh2o2** [comment]
I think we can go ahead and close this since we've done away with the RR Lyrae code altogether. What do you think?

**Comment by jakevdp** [comment]
Sounds good
